name: Check for broken links

on:
  push:
  pull_request:
  schedule:
    # Runs weekly on Monday at 00:00
    - cron: "0 0 * * 1"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: 🔗 Check Links
        uses: lycheeverse/lychee-action@v2
        with:
            lycheeVersion: latest
            format: markdown
            args: >
              --base https://pestphp.com
              --user-agent "Mozilla 5.0"
              --exclude "https?://(www\.)?(twitter\.com|instagram\.com|linkedin\.com)"
              --max-retries 5
              --verbose
              --no-progress
              "**/*.md"
